repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-bashbang-style
      - id: check-docker
      - id: check-json
      - id: check-merge-conflict
      - id: check-pip-install
      - id: check-yaml
      - id: trailing-whitespace
