# Default Hydra Configuration for DLAMP ML module

model:
  in_features: 10
  hidden_dim: 32
  out_features: 1
  lr: 0.001

data:
  batch_size: 32
  num_samples: 100

trainer:
  max_epochs: 2
  accelerator: "cpu"
  devices: 1
